# DATASOURCE
jdbc:
    dataSourceClassName: coracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.21.4.253:1521:ofpay
    username: ofpayuser
    password: ofcard
    maxActive: 5
    initialSize: 1
    maxIdle: 5
    minIdle: 1
# MyBatis
mybatis:
    typeAliasesPackage: com.kan.generator.domain
    mapperLocations: com.kan.generator.mapper.*.xml
    configLocation: classpath:/mybatis-config.xml
